// Header comment script
// input is already parsed JSON object

// Generate header comment
const header = `/**
 * ${input.tableName} model
 * Generated at: ${new Date().toLocaleString()}
 * Table: ${input.tableName}
 * Field count: ${input.fields.length}
 * Do not edit this file manually
 */

`;

// Get current generated code
let result = tsCode;

// If no header comment, add one
if (!result.includes('/**')) {
    result = header + result;
}

// Set output result
output = result;